server:
  port: 8081

spring:
  application:
    name: payment


  datasource:
    url: jdbc:postgresql://localhost:5433/payment_db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
     serialization:
        indent_output: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE